name: rsync-to-dev
on:
  push:
    branches:
    - main

jobs:
  rsync-to-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Comment to explain line below
      # - run: sh ./getsizes.sh
      - run: scp -i ${{ secrets.DEPLOY_KEY }} ./styles.css root@dev.tate.digital:/home/tatedev/tests