name: rsync-to-dev
on:
  push:
    branches:
    - main

jobs:
  rsync-to-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          # port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "images/*.jpg"
          target: "/var/www/html/dept2/webp/"
          # target: "/home/tatedev/tests/image-compare/"