name: rsync-to-dev
on:
  push:
    branches:
    - main

jobs:
  rsync-to-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: sh ./getsizes.sh
      - uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avvzr --exclude=".*" --delete
          path: ./
          remote_path: /home/tatedev/tests/image-compare
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_port: ${ secrets.DEPLOY_PORT }
          remote_key: ${{ secrets.DEPLOY_KEY }} 