name: rsync-to-dev
on:
  push:
    branches:
    - main

jobs:
  rsync-to-dev:
    runs-on: ubuntu-latest
    steps:
      # - uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.DEPLOY_HOST }}
      #     username: ${{ secrets.DEPLOY_USER }}
          # port: ${{ secrets.DEPLOY_PORT }}
          # key: ${{ secrets.DEPLOY_KEY }}
          # source: "images/*.jpg, images/*.webp"
          # target: "/var/www/html/dept2/webp/"
          # target: "/home/tatedev/tests/image-compare/"
      - uses: burnett01/rsync-deployments@4.1
        with:
            switches: -avvvzr --delete --exclude=".*"
            path: images/
            remote_path: /var/www/html/dept2/webp/
            remote_host: ${{ secrets.DEPLOY_HOST }}
            remote_user: ${{ secrets.DEPLOY_USER }}
            remote_key: ${{ secrets.DEPLOY_KEY }}